/**
 * Master Data - Jabatan/Posisi
 * Data master jabatan untuk sistem payroll perkebunan sawit
 */

export interface MasterPosition {
  id: string;
  code: string;
  name: string;
  level: 'karyawan' | 'pegawai' | 'pkwt' | 'staff';
  description: string;
  baseSalary: number;
  allowanceJabatan: number;
  allowanceSkill: number;
  isActive: boolean;
  employeeCount: number;
}

export const MASTER_POSITIONS: MasterPosition[] = [
  {
    id: '1',
    code: 'PMN',
    name: 'Pemanen',
    level: 'karyawan',
    description: 'Karyawan lapangan pemanen TBS',
    baseSalary: 3000000,
    allowanceJabatan: 500000,
    allowanceSkill: 300000,
    isActive: true,
    employeeCount: 85,
  },
  {
    id: '2',
    code: 'SPR-PMN',
    name: 'Supervisor Pemanen',
    level: 'staff',
    description: 'Supervisor tim pemanen',
    baseSalary: 5500000,
    allowanceJabatan: 1500000,
    allowanceSkill: 800000,
    isActive: true,
    employeeCount: 8,
  },
  {
    id: '3',
    code: 'DRV',
    name: 'Supir',
    level: 'karyawan',
    description: 'Supir angkutan TBS',
    baseSalary: 3500000,
    allowanceJabatan: 600000,
    allowanceSkill: 400000,
    isActive: true,
    employeeCount: 15,
  },
  {
    id: '4',
    code: 'MKN',
    name: 'Mekanik',
    level: 'pegawai',
    description: 'Mekanik perawatan alat berat',
    baseSalary: 4500000,
    allowanceJabatan: 1000000,
    allowanceSkill: 700000,
    isActive: true,
    employeeCount: 12,
  },
  {
    id: '5',
    code: 'SPR-MNT',
    name: 'Supervisor Maintenance',
    level: 'staff',
    description: 'Supervisor tim maintenance',
    baseSalary: 6000000,
    allowanceJabatan: 1800000,
    allowanceSkill: 1000000,
    isActive: true,
    employeeCount: 3,
  },
  {
    id: '6',
    code: 'ADM',
    name: 'Admin',
    level: 'pegawai',
    description: 'Staff administrasi',
    baseSalary: 4000000,
    allowanceJabatan: 800000,
    allowanceSkill: 500000,
    isActive: true,
    employeeCount: 8,
  },
  {
    id: '7',
    code: 'ASST-MGR',
    name: 'Asisten Manajer',
    level: 'staff',
    description: 'Asisten manajer operasional kebun',
    baseSalary: 8000000,
    allowanceJabatan: 3000000,
    allowanceSkill: 1500000,
    isActive: true,
    employeeCount: 5,
  },
  {
    id: '8',
    code: 'PRWT',
    name: 'Perawatan',
    level: 'karyawan',
    description: 'Perawatan tanaman dan pemupukan',
    baseSalary: 2800000,
    allowanceJabatan: 450000,
    allowanceSkill: 250000,
    isActive: true,
    employeeCount: 22,
  },
  {
    id: '9',
    code: 'PKWT-PMN',
    name: 'PKWT Pemanen',
    level: 'pkwt',
    description: 'Karyawan kontrak pemanen musiman',
    baseSalary: 2500000,
    allowanceJabatan: 350000,
    allowanceSkill: 200000,
    isActive: true,
    employeeCount: 18,
  },
  {
    id: '10',
    code: 'MDR-PMN',
    name: 'Mandor Panen',
    level: 'pegawai',
    description: 'Mandor tim pemanen',
    baseSalary: 4200000,
    allowanceJabatan: 900000,
    allowanceSkill: 600000,
    isActive: true,
    employeeCount: 12,
  },
  {
    id: '11',
    code: 'OPR-MSN',
    name: 'Operator Mesin',
    level: 'karyawan',
    description: 'Operator mesin dan alat berat',
    baseSalary: 3200000,
    allowanceJabatan: 550000,
    allowanceSkill: 350000,
    isActive: true,
    employeeCount: 10,
  },
  {
    id: '12',
    code: 'MGR-ADM',
    name: 'Manajer Administrasi',
    level: 'staff',
    description: 'Manajer administrasi dan keuangan',
    baseSalary: 10000000,
    allowanceJabatan: 4000000,
    allowanceSkill: 2000000,
    isActive: true,
    employeeCount: 2,
  },
  {
    id: '13',
    code: 'MGR-FIN',
    name: 'Manajer Keuangan',
    level: 'staff',
    description: 'Manajer keuangan perusahaan',
    baseSalary: 12000000,
    allowanceJabatan: 5000000,
    allowanceSkill: 2500000,
    isActive: true,
    employeeCount: 2,
  },
];
